In [3]:
import numpy as np


In [4]:
a = np.array([1,2,3])
b = np.array([[1,2,3, 8], [4,5,6, 7]])


In [5]:
print(b)


[[1 2 3 8]
 [4 5 6 7]]


In [6]:
zeros = np.zeros((2,3))
ones = np.ones((2,3))

In [7]:
print(zeros)
print(ones)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
range_arr = np.arange(2,20,5)
print(range_arr)

[ 2  7 12 17]


In [10]:
linspace_arr = np.linspace(2, 5, 5)
print(linspace_arr)

[2.   2.75 3.5  4.25 5.  ]


In [11]:
# Shape of the array (row , column)
print(b.shape)

# Dimension of array (1 / 2 / 3)

print(b.ndim)

# Total elements in array
print(b.size)

# Datatype of array
print(b.dtype)

(2, 4)
2
8
int64


In [12]:
c = np.zeros((2,3,3,4))

In [13]:
print(c)

[[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]]


In [14]:
print(c.size)

72


Indexing and Slicing

In [15]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])
print(arr[-1])

print(arr[arr.size - 1])
print(arr[1:4])

10
50
50
[20 30 40]


# 2D Slicing

In [16]:
mat = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [17]:
print(mat[1, 1])     
print(mat[:, 2])
print(mat[1, :])

5
[3 6 9]
[4 5 6]


# Vectorized operations

In [18]:
a = np.array([1, 2, 3])

print(a + 10)
print(a * 2)
print(a ** 3)

[11 12 13]
[2 4 6]
[ 1  8 27]


## Broadcasting

### Allows operations between arrays of different shapes.

In [19]:
mat = np.array([[1,2,3],
                [4,5,6], [7,8,9]])

vec = np.array([10, 20, 30])

print(mat + vec)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


# Boolean masking

In [20]:
arr = np.array([10, 15, 20, 25])

mask = arr > 15

print(f"Mask : {mask}")
print(type(arr))
print(arr[mask])

boolArray = np.array([False, True, True, False])
arr[boolArray]

print(arr[arr % 2 == 0])  # even numbers

Mask : [False False  True  True]
<class 'numpy.ndarray'>
[20 25]
[10 20]


# Reshaping & stacking

## Reshaping

In [21]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [22]:
arr.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
arr.reshape(-1, 2) # Auto Infer

array([[0, 1],
       [2, 3],
       [4, 5]])

## Stacking

In [24]:
a = np.array([1,2])
b = np.array([3,4])

In [25]:
np.vstack((a, b))


array([[1, 2],
       [3, 4]])

In [26]:
np.hstack((a, b))


array([1, 2, 3, 4])

# Aggregations & statistics

In [27]:
arr = np.array([[1,2,3],
                [4,-1,6]])

print(arr.sum())
print(arr.sum(axis=0))  # column-wise sum
print(arr.mean())
print(arr.max())
print(arr.argmin())     # Index of min value
print(arr.argmax())     # Index of max value

15
[5 1 9]
2.5
6
4
5


# Random numbers

In [28]:

np.random.rand(5) # uniform distribution [0,1)

array([0.62612195, 0.37329831, 0.26884043, 0.86691511, 0.35317025])

In [29]:
np.random.randn(3)  # normal (Gaussian) distribution

array([ 0.30309294, -0.96958564, -0.31747254])

In [30]:
np.random.randint(1, 10, size=3)


array([1, 7, 4])

In [31]:
np.random.seed(42)
np.random.randn(3)  

array([ 0.49671415, -0.1382643 ,  0.64768854])

In [32]:
rng = np.random.default_rng()

rng.random(3)


array([0.86820895, 0.96829165, 0.18334324])

In [33]:
rng.standard_normal(3)

array([-0.0570392 , -0.22852227, -0.28283378])

In [34]:
rng = np.random.default_rng(42)


In [35]:
rng.random(3)

array([0.77395605, 0.43887844, 0.85859792])

# Linear algebra basics

In [36]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

In [37]:
print(A @ B )              # matrix multiplication
print(np.dot(A, B)) 
print(np.linalg.det(A)) 
print(np.linalg.inv(A)) 
print(np.linalg.eig(A)) 

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


# Performance tip (important)

In [38]:
# Avoid loops:

# Bad
result = []
for x in arr:
    result.append(x * 2)

# Good
result = arr * 2

# Common Mistakes

In [39]:
arr = np.array([[1,2,3], [4,5,6]])

print(f"arr : {arr}")

b = arr[1:3]
print (f"b : {b}")
b[0] = 999      # Also changes arr


arr : [[1 2 3]
 [4 5 6]]
b : [[4 5 6]]


In [40]:
print(b)
print(arr)

[[999 999 999]]
[[  1   2   3]
 [999 999 999]]
